services:

  postgres-order:
    image: postgres:17
    container_name: postgres-order
    restart: unless-stopped

    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_order_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql-inventory:
    image: mysql:8.4
    container_name: mysql-inventory
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_inventory_data:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u inventory_user -pinventory_password"]
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: keycloak
    restart: unless-stopped

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    command:
      - start-dev

    ports:
      - "8090:8080"

volumes:
  postgres_order_data:
  mysql_inventory_data: