server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  ##anadimos el oauth2 osea usaremos lo mismo del gateway
  security:
    oauth2:
        resourceserver:
            jwt:
            issuer-uri: http://localhost:8090/realms/reto-backend

inventory:
  service:
    url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info