server:
  port: 8081

spring:
  application:
    name: order-service

  ## cambiabos las rutas que estaban en host a los enviroments del docker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
    ## estoy usando las credenciales de docker si lo quieres probar en tu maquina tienes que
    ## poner las credenciales de tu motor de base de datos
    ## ejemplo el mio es user: potgres, pass: potgres , ahi si me correo el modulo
    ## pero tu de seguro lo veras como user: order_user , pass: order_password
    ## haciendo referencia al modulo
    ## solo queria dejar esto claro para que cuando lo pruebes no te bote error
    ## igual lo voy a documentar en el readme en la parte ultima para dejarlo mas claro
    username: ${SPRING_DATASOURCE_USERNAME:order_user}
    password: ${SPRING_DATASOURCE_PASSWORD:order_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ##para que se pueda importar los datos de prueba
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  ##anadimos el oauth2 osea usaremos lo mismo del gateway
  security:
    oauth2:
        resourceserver:
            jwt:
              issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8090/realms/reto-backend}

inventory:
  service:
    ##cambiamos la url por una condicional
    ##url: http://localhost:8082
    ##concordancia con el enviroment del docker
    url: ${INVENTORY_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info