server:
  port: 8081

spring:
  application:
    name: order-service

  ## cambiabos las rutas que estaban en host a los enviroments del docker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:order_user}
    password: ${SPRING_DATASOURCE_PASSWORD:order_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ##para que se pueda importar los datos de prueba
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  ##anadimos el oauth2 osea usaremos lo mismo del gateway
  security:
    oauth2:
        resourceserver:
            jwt:
              issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8090/realms/reto-backend}

inventory:
  service:
    ##cambiamos la url por una condicional
    ##url: http://localhost:8082
    ##concordancia con el enviroment del docker
    url: ${INVENTORY_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info